### ISSUE TITLE
Proposed New Word urn:cite:hmt:msA.101r: ουρανῶθεν

### ISSUE THREAD

**Issue by StephanieML** [homermultitext/morpheus#5]
passage: urn:cts:greekLit:tlg5026.msA.hmt:8.17
surface: ουρανῶθεν

Even normalized this word isn't passing verification. So normalized would be οὐρανῶθεν 
and it means something like "coming from heaven"

**Comment by neelsmith** [comment]
It's a "sic": normal orthography is οὐράνοθεν
